// Timeline configuration constants
export const TIMELINE_CONFIG = {
  PAD_DAYS: 2,
  HEADER_HEIGHT: 48,
  MIN_ROW_HEIGHT: 40,
  MAX_ROW_HEIGHT: 64,
  MIN_BAR_PIXELS: 64,
  TARGET_BODY_HEIGHT_RATIO: 0.6,
  MAX_BODY_HEIGHT: 700,
  LABEL_PADDING: 16,
  ITEM_GAP: 8,
  BORDER_PADDING: 4
}; 